### PR TITLE
Rename changelog.md to README.md

### PR DESCRIPTION
**Pull request by Xethron**
Opening the repository for the first time is a bit confusing, especially seeing as there is no readme and barely any files.

This commit renames the changelog.md to README.md, and Github will automatically display the file when opening the repository.

### CODE REVIEW

**Comment by Daniel15** [comment]
I don't understand the point of this repo if there's no source code in it.

**Comment by Daij-Djan** [comment]
this PR is as pointless as this repo I fear. There isnt any code anyway :)

**Comment by gingerbeardman** [comment]
I guess this project is dead?

**Comment by blyszcz** [comment]
Bump gingerbeardman question

**Comment by tayvano** [comment]
If you ain't gunna maintain it, open source it so others can. Don't be a butthole.

**Comment by mightyBroccoli** [comment]
We could just fork and maintain the plugins ourselfs, just the main application is tiers the plugins are open source arent they?

**Comment by tayvano** [comment]
I'm trying to figure out notifications currently. Shit is so stupidly obfuscated and wrapped in electron and apple bullshit. Easy to maintain plugins, the app itself needs some major upgades though - like basic oauth support and giving plugins access to notifs.

Honestly anyone with half a brain and ability to write an open api that makes sense could just rebuild this app and make it very easily for any dev to hook in and build a plugin. It is just electron wrapping websites, obfuscated to seem fancier than it is. They've probably spent more time trying to hide what they've done than actually building stuff - no joke. 

There are obviously a ton of people and devs who find hooking into website and having native notifis from these websites very useful (including me). 

Here's the notif stuff I've managed to grab:

```( function( exports, require, module, __filename, __dirname, process, global ) {
//    var _0x3ed2 = [
//        "use strict",
//        "electron",1
//        "ipcRenderer",2
//        "Notification",3
//        "service-notification-notifier-custom",4
//        "sendToHost",5
//        "undefined",6
//        "UTIL_INIT_NOTIF_OVERRIDES",7
//        "prototype",8
//        "permission",9
//        "granted"10
//    ];
    _0x3ed2[ 0 ];
    var _require = require(  "electron" ),
        ipcRenderer = _require.ipcRenderer;
        windowNotifications = window.Notification;

    var NotificationProxy = function( i, o ) { 
      ipcRenderer.sendToHost( "service-notification-notifier-custom", { title: i, options: o } ) 
    };

    if ( undefined != typeof global."UTIL_INIT_NOTIF_OVERRIDES" && 2 === global."UTIL_INIT_NOTIF_OVERRIDES" ) {
        var notif_proto_old = window.Notification.prototype;
        window.Notification = NotificationProxy, window.Notification.permission = "granted", window.Notification.prototype = notif_proto_old 
    } else { 
        window.Notification = NotificationProxy, window.Notification.permission = "granted" 
    }

} );
```

in your plugin you can use:

```
    new windowNotifications('Title', {
      body              : "Body",
      data              : null,
      dir               : "auto",
      icon              : "",
      lang              : "",
      onclick           : null,
      onclose           : null,
      onerror           : null,
      onshow            : null,
      renotify          : false,
      requireInteraction: false,
      silent            : false,
      tag               : "",
      timestamp         : 1495966488015,
      title             : "Title",
    })
```

FWIW, if someone does want to rebuild, I would be hestiant to use electron unless they are prepared to find a way to manage the memory leaks and garbage collector issues that plague every electron app.

**Comment by jtibrewala** [comment]
Are there any alternative equivalents to Franz that we can all migrate to?

**Comment by Daij-Djan** [comment]
Rambox.pro. Same tool. Real open source. 

Von meinem iPhone gesendet

**Comment by jtibrewala** [comment]
Brilliant.  Thanks much.  And goodbye Franz.

**Comment by gingerbeardman** [comment]
Does Rambox have plugins?

Last time I checked it didn't.

But it does have newer Electron.

**Comment by Daij-Djan** [comment]
It does. Custom integrations

Von meinem iPhone gesendet

> Am 28.05.2017 um 17:00 schrieb Matt Sephton <notifications@github.com>:
> 
> Does Rambox have plugins?
> 
> Last time I checked it didn't.
> 
> But it does have newer Electron.
>

**Comment by Daniel15** [comment]
> Are there any alternative equivalents to Franz that we can all migrate to?

Is there really much value in an app like Franz or Rambox that simply contains a bunch of web views? It's still a disparate experience across all the supported networks. I miss true multi-protocol IM apps like Digsby (which is basically dead now) and Trillian, where you can do things like combining contacts across multiple networks so they just appear as a single contact in your contact list.

It looks like Trillian is still around, I haven't used it in years though. Pidgin is decent and open-source, but is missing newer services like Facebook and Discord, until people write plugins for those services.

On the other hand, just using the upstream service in a webview means that you always have the latest features. It's a tradeoff.

**Comment by tayvano** [comment]
The value it provides me is having a place that notifies me of my 8000 different comm channels. I'm a freelancer and I accidentally built a Foss on the side, so I've got about 4 asanas, 2 grooves, 8 Trello boards, Skype, email, slack, Hangouts, GitHub, bitbucket, Facebook, Twitter, Instagram, and more. It's fucking insane. 

For a while I had all notifications routed through slack (this also gives me an easy way to mute depending on what I'm currently working on) but having Franz open allows me to be notified and respond. In particular, groove and Asana have long initial load times and in the 5 seconds it takes for me to click and load the site, I am usually distracted away by another notification. 

Of course it would be better to have a core ____ that all these share that anything could hook into and provide an interface for, but how would these billion dollar companies control their revenue that they make off controlling your data if that were the case. 🙄

Its also really nice that I can have my 2 grooves open simultaneously bc groove only allows you to be logged into one team at anytime, so before I was constantly switching. 

So yeah. Value is different for everyone I guess. 😊

**Comment by Daniel15** [comment]
I guess I could rephrase my question - What does Franz (or Rambox) do that couldn't be done simply via browser extensions without having to use an entirely separate app?

**Comment by tayvano** [comment]
The separate app is actually the thing that I like. It's just the *one* separate app with all these "apps" inside. I don't like having 20 apps. Open.

My browser is for browsing. It's for opening tabs and closing them and developing and debugging and everything in between. I lose browser windows and tabs often and occasionally have to cmd+q Chrome in order to start fresh and calm my computer, who often thinks she's a rocketship.

By having these things - like Asana which is managing my tasks or groove which I use to communicate with the client - in a separate app, I can use cmd+spacebar to alfred to Franz, or have it open on a separate screen, and not have it be disrupted by whatever is happening in my browser. 

I don't *want* to click a link from Asana and have it pop up in a new tab in that window. I *want* it to pop up in a separate window on my large desktop. That way I can have the email / task information open on screen 1 + see what they are talking about on screen 2.

Plus, easily mutable, native notifications > chrome notifs.

**Review by LoicSenseFly — APPROVED** [review]

**Comment by gnidorah** [comment]
@Daniel15 It gets you correct counters in unified way:
1. tray icon that you have unread messages
2. per tab counters, so you know where you most needed

**Comment by Xethron** [comment]
This repo is obsolete, closing PR

**Pull request closed without merging**
